export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  category: string
  description: string
  tags: string[]
  stock: number
  isBestSeller?: boolean
  isNew?: boolean
  isLowStock?: boolean
}

export const categories = [
  { id: 'adult-food', name: 'Adult Food' },
  { id: 'kitten-food', name: 'Kitten Food' },
  { id: 'collar', name: 'Collar' },
  { id: 'clumping-cat-litter', name: 'Clumping Cat Litter' },
  { id: 'cat-litter-accessories', name: 'Cat Litter Accessories' },
  { id: 'harness', name: 'Harness' },
  { id: 'cat-tick-flea-control', name: 'Cat Tick & Flea Control' },
  { id: 'deworming-tablet', name: 'Deworming Tablet' },
  { id: 'cat-pouches', name: 'Cat Pouches' },
  { id: 'sunglass', name: 'Sunglass' }
]

// Mock data - MongoDB-ready structure
export const productsData: Record<string, Product[]> = {
  'adult-food': [
    {
      id: 'af001',
      name: 'Royal Canin Adult Cat Food',
      price: 2400,
      originalPrice: 2800,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 234,
      category: 'adult-food',
      description: 'Premium dry cat food for adult cats with balanced nutrition.',
      tags: ['Premium', 'Adult'],
      stock: 45,
      isBestSeller: true,
    },
    {
      id: 'af002',
      name: 'Whiskas Adult Dog Food',
      price: 850,
      image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 189,
      category: 'adult-food',
      description: 'Delicious ocean fish flavor wet food for cats.',
      tags: ['Wet Food', 'Fish'],
      stock: 78,
    },
    {
      id: 'af003',
      name: 'Hills Science Diet Adult Food',
      price: 3200,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 156,
      category: 'adult-food',
      description: 'Specially formulated nutrition for growing kittens.',
      tags: ['Kitten', 'Science Diet'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'af004',
      name: 'Purina Pro Plan Adult Dog',
      price: 1950,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 203,
      category: 'adult-food',
      description: 'High-protein dry food for active adult cats.',
      tags: ['High Protein', 'Adult'],
      stock: 8,
      isLowStock: true,
    },
  ],
  'kitten-food': [
    {
      id: 'kf001',
      name: 'Royal Canin Kitten Food',
      price: 3200,
      originalPrice: 3600,
      image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 342,
      category: 'kitten-food',
      description: 'Complete nutrition for adult dogs with real chicken.',
      tags: ['Adult', 'Chicken'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'kf002',
      name: 'Purina Pro Plan Kitten',
      price: 4500,
      image: 'https://images.unsplash.com/photo-1552053628-0dcb5a60e3de?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 189,
      category: 'kitten-food',
      description: 'Specialized nutrition for large breed puppies.',
      tags: ['Puppy', 'Large Breed'],
      stock: 34,
    },
    {
      id: 'kf003',
      name: 'Hills Science Diet Kitten Food',
      price: 5200,
      image: 'https://images.unsplash.com/photo-1587402092301-725e37c70fd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 98,
      category: 'kitten-food',
      description: 'Therapeutic nutrition for dogs with special dietary needs.',
      tags: ['Prescription', 'Therapeutic'],
      stock: 12,
      isNew: true,
    },
    {
      id: 'kf004',
      name: 'Drools Kitten Food',
      price: 2100,
      image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.4,
      reviews: 267,
      category: 'kitten-food',
      description: 'Affordable complete nutrition for adult dogs.',
      tags: ['Adult', 'Value'],
      stock: 5,
      isLowStock: true,
    },
  ],
  'collar': [
    {
      id: 'col001',
      name: 'Adjustable Pet Collar',
      price: 450,
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 156,
      category: 'collar',
      description: 'Fun interactive wand toy to keep cats active and engaged.',
      tags: ['Interactive', 'Cat'],
      stock: 89,
      isBestSeller: true,
    },
    {
      id: 'col002',
      name: 'Leather Dog Collar',
      price: 850,
      image: 'https://images.unsplash.com/photo-1605043204319-d14e5ba4719e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 234,
      category: 'collar',
      description: 'Durable rubber toy perfect for stuffing with treats.',
      tags: ['Durable', 'Dog'],
      stock: 67,
    },
    {
      id: 'col003',
      name: 'Reflective Cat Collar',
      price: 320,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 189,
      category: 'collar',
      description: 'Soft mice toys filled with premium catnip.',
      tags: ['Catnip', 'Pack'],
      stock: 45,
      isNew: true,
    },
    {
      id: 'col004',
      name: 'Bell Collar for Cats',
      price: 650,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 145,
      category: 'collar',
      description: 'High-value treats perfect for training sessions.',
      tags: ['Training', 'Treats'],
      stock: 7,
      isLowStock: true,
    },
  ],
  'clumping-cat-litter': [
    {
      id: 'cll001',
      name: 'Clumping Cat Litter',
      price: 2800,
      originalPrice: 3200,
      image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 98,
      category: 'clumping-cat-litter',
      description: 'Complete grooming kit with brushes, clippers, and accessories.',
      tags: ['Professional', 'Complete Kit'],
      stock: 23,
      isBestSeller: true,
    },
    {
      id: 'cll002',
      name: 'Odor Control Clumping Litter',
      price: 950,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 167,
      category: 'clumping-cat-litter',
      description: 'Gentle shampoo and conditioner for sensitive pet skin.',
      tags: ['Gentle', 'Set'],
      stock: 54,
    },
    {
      id: 'cll003',
      name: 'Natural Clumping Cat Litter',
      price: 450,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 234,
      category: 'clumping-cat-litter',
      description: 'Safe and easy-to-use nail clippers for all pet sizes.',
      tags: ['Safety', 'Universal'],
      stock: 78,
      isNew: true,
    },
    {
      id: 'cll004',
      name: 'Low Dust Clumping Litter',
      price: 750,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 156,
      category: 'clumping-cat-litter',
      description: 'Reduces shedding by up to 90% with gentle bristles.',
      tags: ['De-shedding', 'Gentle'],
      stock: 3,
      isLowStock: true,
    },
  ],
  'cat-litter-accessories': [
    {
      id: 'cla001',
      name: 'Litter Scoop',
      price: 1200,
      image: 'https://images.unsplash.com/photo-1587402092301-725e37c70fd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 123,
      category: 'cat-litter-accessories',
      description: 'Daily multivitamin for optimal pet health and immunity.',
      tags: ['Multivitamin', 'Daily'],
      stock: 67,
      isBestSeller: true,
    },
    {
      id: 'cla002',
      name: 'Litter Box Liners',
      price: 850,
      image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 189,
      category: 'cat-litter-accessories',
      description: '8-month protection against fleas and ticks.',
      tags: ['Prevention', '8-month'],
      stock: 45,
    },
    {
      id: 'cla003',
      name: 'Cat Litter Mat',
      price: 1500,
      image: 'https://images.unsplash.com/photo-1552053628-0dcb5a60e3de?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 87,
      category: 'cat-litter-accessories',
      description: 'Supports digestive health with beneficial probiotics.',
      tags: ['Probiotics', 'Digestive'],
      stock: 34,
      isNew: true,
    },
    {
      id: 'cla004',
      name: 'Litter Disposal Bags',
      price: 650,
      image: 'https://images.unsplash.com/photo-1605043204319-d14e5ba4719e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.4,
      reviews: 156,
      category: 'cat-litter-accessories',
      description: 'Gentle ear cleaning solution for regular maintenance.',
      tags: ['Gentle', 'Maintenance'],
      stock: 9,
      isLowStock: true,
    },
  ],
  'harness': [
    {
      id: 'har001',
      name: 'Adjustable Pet Harness',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 234,
      category: 'harness',
      description: 'Comfortable and secure harness for daily walks.',
      tags: ['Adjustable', 'Comfortable'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'har002',
      name: 'No-Pull Dog Harness',
      price: 750,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 189,
      category: 'harness',
      description: 'Durable stainless steel bowls, set of 2.',
      tags: ['Stainless Steel', 'Set of 2'],
      stock: 78,
    },
    {
      id: 'har003',
      name: 'Front-Clip Harness',
      price: 2400,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 167,
      category: 'harness',
      description: 'Memory foam pet bed for joint support and comfort.',
      tags: ['Orthopedic', 'Memory Foam'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'har004',
      name: 'Light-Up Harness',
      price: 650,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 145,
      category: 'harness',
      description: '16ft retractable leash with ergonomic handle.',
      tags: ['Retractable', '16ft'],
      stock: 4,
      isLowStock: true,
    },
  ],
  'cat-tick-flea-control': [
    {
      id: 'ctf001',
      name: 'Cat Tick & Flea Collar',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 234,
      category: 'cat-tick-flea-control',
      description: 'Comfortable and secure harness for daily walks.',
      tags: ['Adjustable', 'Comfortable'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'ctf002',
      name: 'Flea & Tick Spot-On Treatment',
      price: 750,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 189,
      category: 'cat-tick-flea-control',
      description: 'Durable stainless steel bowls, set of 2.',
      tags: ['Stainless Steel', 'Set of 2'],
      stock: 78,
    },
    {
      id: 'ctf003',
      name: 'Flea & Tick Shampoo',
      price: 2400,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 167,
      category: 'cat-tick-flea-control',
      description: 'Memory foam pet bed for joint support and comfort.',
      tags: ['Orthopedic', 'Memory Foam'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'ctf004',
      name: 'Flea Comb',
      price: 650,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 145,
      category: 'cat-tick-flea-control',
      description: '16ft retractable leash with ergonomic handle.',
      tags: ['Retractable', '16ft'],
      stock: 4,
      isLowStock: true,
    },
  ],
  'deworming-tablet': [
    {
      id: 'dew001',
      name: 'Deworming Tablet for Cats',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 234,
      category: 'deworming-tablet',
      description: 'Comfortable and secure harness for daily walks.',
      tags: ['Adjustable', 'Comfortable'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'dew002',
      name: 'Broad Spectrum Dewormer',
      price: 750,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 189,
      category: 'deworming-tablet',
      description: 'Durable stainless steel bowls, set of 2.',
      tags: ['Stainless Steel', 'Set of 2'],
      stock: 78,
    },
    {
      id: 'dew003',
      name: 'Puppy Deworming Suspension',
      price: 2400,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 167,
      category: 'deworming-tablet',
      description: 'Memory foam pet bed for joint support and comfort.',
      tags: ['Orthopedic', 'Memory Foam'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'dew004',
      name: 'Dog Dewormer Chews',
      price: 650,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 145,
      category: 'deworming-tablet',
      description: '16ft retractable leash with ergonomic handle.',
      tags: ['Retractable', '16ft'],
      stock: 4,
      isLowStock: true,
    },
  ],
  'cat-pouches': [
    {
      id: 'cp001',
      name: 'Wet Cat Food Pouches',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 234,
      category: 'cat-pouches',
      description: 'Comfortable and secure harness for daily walks.',
      tags: ['Adjustable', 'Comfortable'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'cp002',
      name: 'Salmon Flavor Cat Pouches',
      price: 750,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 189,
      category: 'cat-pouches',
      description: 'Durable stainless steel bowls, set of 2.',
      tags: ['Stainless Steel', 'Set of 2'],
      stock: 78,
    },
    {
      id: 'cp003',
      name: 'Tuna Flavor Cat Pouches',
      price: 2400,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 167,
      category: 'cat-pouches',
      description: 'Memory foam pet bed for joint support and comfort.',
      tags: ['Orthopedic', 'Memory Foam'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'cp004',
      name: 'Chicken Flavor Cat Pouches',
      price: 650,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 145,
      category: 'cat-pouches',
      description: '16ft retractable leash with ergonomic handle.',
      tags: ['Retractable', '16ft'],
      stock: 4,
      isLowStock: true,
    },
  ],
  'sunglass': [
    {
      id: 'sun001',
      name: 'Pet Sunglasses',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 234,
      category: 'sunglass',
      description: 'Comfortable and secure harness for daily walks.',
      tags: ['Adjustable', 'Comfortable'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'sun002',
      name: 'Dog Goggles',
      price: 750,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 189,
      category: 'sunglass',
      description: 'Durable stainless steel bowls, set of 2.',
      tags: ['Stainless Steel', 'Set of 2'],
      stock: 78,
    },
    {
      id: 'sun003',
      name: 'Fashion Pet Sunglasses',
      price: 2400,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 167,
      category: 'sunglass',
      description: 'Memory foam pet bed for joint support and comfort.',
      tags: ['Orthopedic', 'Memory Foam'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'sun004',
      name: 'UV Protection Dog Glasses',
      price: 650,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 145,
      category: 'sunglass',
      description: '16ft retractable leash with ergonomic handle.',
      tags: ['Retractable', '16ft'],
      stock: 4,
      isLowStock: true,
    },
  ],
}

export function getProductsByCategory(categoryId: string): Product[] {
  return productsData[categoryId] || []
}

export function getCategoryAnalytics(categoryId: string) {
  const products = getProductsByCategory(categoryId)

  if (products.length === 0) {
    return {
      lowestPriced: null,
      highestPriced: null,
      highestRated: null,
      bestSeller: null,
    }
  }

  const lowestPriced = products.reduce((min, product) =>
    product.price < min.price ? product : min
  )

  const highestPriced = products.reduce((max, product) =>
    product.price > max.price ? product : max
  )

  const highestRated = products.reduce((max, product) =>
    product.rating > max.rating ? product : max
  )

  const bestSeller = products.find(product => product.isBestSeller) || products[0]

  return {
    lowestPriced,
    highestPriced,
    highestRated,
    bestSeller,
  }
}